name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: CoderSerio
          MAX_LINES: 5
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://furrycoder.com/rss.xml"
          max_post_count: 5
          commit_message: "chore: update README"
